Added first version of the new test-app and its run script

diff --git a/templates/test/run b/templates/test/run
--- a/templates/test/run
+++ b/templates/test/run
@@ -1,11 +1,7 @@
-
 #!/bin/bash
 #
-# The 'run' performs a simple test that verifies the S2I image.
-# The main focus here is to exercise the S2I scripts.
-#
-# For more information see the documentation:
-# https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md
+# The 'run' performs a simple test that verifies that STI image.
+# The main focus here is to excersise the STI scripts.
 #
 # IMAGE_NAME specifies a name of the candidate image used for testing.
 # The image has to be available before this script is executed.
@@ -25,12 +21,16 @@ image_dir=$($READLINK_EXEC -zf ${test_dir}/..)
 scripts_url="file://${image_dir}/.s2i/bin"
 cid_file=$($MKTEMP_EXEC -u --suffix=.cid)
 
-# Since we built the candidate image locally, we don't want S2I to attempt to pull
+# Since we built the candidate image locally, we don't want S2I attempt to pull
 # it from Docker hub
-s2i_args="--force-pull=false --loglevel=2"
+s2i_args="--force-pull=false --loglevel=2 "
 
-# Port the image exposes service to be tested
+# TODO: This should be part of the image metadata
 test_port=8080
+
+if [ "$DEBUG" != "" ]; then
+  set -x
+fi
 
 image_exists() {
   docker inspect $1 &>/dev/null
@@ -44,6 +44,10 @@ container_ip() {
   docker inspect --format="{{ .NetworkSettings.IPAddress }}" $(cat $cid_file)
 }
 
+container_logs() {
+  docker logs $(cat $cid_file)
+}
+
 run_s2i_build() {
   s2i build --incremental=true ${s2i_args} file://${test_dir}/test-app ${IMAGE_NAME} ${IMAGE_NAME}-testapp
 }
@@ -53,21 +57,17 @@ prepare() {
     echo "ERROR: The image ${IMAGE_NAME} must exist before this script is executed."
     exit 1
   fi
-  # s2i build requires the application is a valid 'Git' repository
+  # TODO: STI build require the application is a valid 'GIT' repository, we
+  # should remove this restriction in the future when a file:// is used.
   pushd ${test_dir}/test-app >/dev/null
   git init
   git config user.email "build@localhost" && git config user.name "builder"
-  git add -A && git commit -m "Sample commit"
+  git add -A && git commit --no-gpg-sign -m "Sample commit"
   popd >/dev/null
-  run_s2i_build
 }
 
 run_test_application() {
-  OUTPUT=$(docker run --rm ${IMAGE_NAME}-testapp)
-  if [[ $OUTPUT == *"Hola"* ]]; then
-    return 0
-  fi
-  return 1
+  docker run --user=100001 --rm --cidfile=${cid_file} -p ${test_port} $1 ${IMAGE_NAME}-testapp
 }
 
 cleanup() {
@@ -77,8 +77,9 @@ cleanup() {
     fi
   fi
   if image_exists ${IMAGE_NAME}-testapp; then
-    docker rmi ${IMAGE_NAME}-testapp
+    docker rmi -f ${IMAGE_NAME}-testapp
   fi
+  rm -rf ${test_dir}/test-app/.git
 }
 
 check_result() {
@@ -90,9 +91,86 @@ check_result() {
   fi
 }
 
-test_usage() {
+wait_for_cid() {
+  local max_attempts=20
+  local sleep_time=1
+  local attempt=1
+  local result=1
+  while [ $attempt -le $max_attempts ]; do
+    [ -f $cid_file ] && [ -s $cid_file ] && break
+    echo "Waiting for container start..."
+    attempt=$(( $attempt + 1 ))
+    sleep $sleep_time
+  done
+}
+
+test_s2i_usage() {
   echo "Testing 's2i usage'..."
   s2i usage ${s2i_args} ${IMAGE_NAME} &>/dev/null
+}
+
+test_docker_run_usage() {
+  echo "Testing 'docker run' usage..."
+  docker run ${IMAGE_NAME} &>/dev/null
+}
+
+test_connection() {
+  echo "Testing HTTP connection..."
+  local max_attempts=10
+  local sleep_time=1
+  local attempt=1
+  local result=1
+  while [ $attempt -le $max_attempts ]; do
+    echo "Sending GET request to http://$(container_ip):${test_port}/"
+    response_code=$(curl -s -w %{http_code} -o /dev/null http://$(container_ip):${test_port}/)
+    status=$?
+    if [ $status -eq 0 ]; then
+      if [ $response_code -eq 200 ]; then
+        result=0
+      fi
+      break
+    fi
+    attempt=$(( $attempt + 1 ))
+    sleep $sleep_time
+  done
+  return $result
+}
+
+test_scl_usage() {
+  local run_cmd="$1"
+  local expected="$2"
+
+  echo "Testing the image SCL enable ..."
+  out=$(docker run --rm ${IMAGE_NAME} /bin/bash -c "${run_cmd}")
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[/bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
+    return 1
+  fi
+  out=$(docker exec $(cat ${cid_file}) /bin/bash -c "${run_cmd}" 2>&1)
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[exec /bin/bash -c "${run_cmd}"] Expected '${expected}', got '${out}'"
+    return 1
+  fi
+  out=$(docker exec $(cat ${cid_file}) /bin/sh -ic "${run_cmd}" 2>&1)
+  if ! echo "${out}" | grep -q "${expected}"; then
+    echo "ERROR[exec /bin/sh -ic "${run_cmd}"] Expected '${expected}', got '${out}'"
+    return 1
+  fi
+}
+
+validate_default_value() {
+  local label=$1
+
+  IFS=':' read -a label_vals <<< $(docker inspect -f "{{index .Config.Labels \"$label\"}}" ${IMAGE_NAME}) 
+  label_var=${label_vals[0]}
+  default_label_val=${label_vals[1]}
+
+  actual_label_val=$(docker run --rm $IMAGE_NAME /bin/bash -c "echo $"$label_var)
+
+  if [ "$actual_label_val" != "$default_label_val" ]; then
+    echo "ERROR default value for $label with environment variable $label_var; Expected $default_label_val, got $actual_label_val"
+    return 1
+  fi
 }
 
 # Build the application image twice to ensure the 'save-artifacts' and
@@ -100,14 +178,28 @@ test_usage() {
 prepare
 run_s2i_build
 check_result $?
-
-# Verify the 'usage' script is working properly
-test_usage
+run_s2i_build
 check_result $?
 
-# Verify we can run the application
-run_test_application
+# Verify the 'usage' script is working properly when running the base image with 's2i usage ...'
+test_s2i_usage
 check_result $?
 
+# Verify the 'usage' script is working properly when running the base image with 'docker run ...'
+test_docker_run_usage
+check_result $?
+
+# Verify that the HTTP connection can be established to test application container
+run_test_application &
+
+# Wait for the container to write it's CID file
+wait_for_cid
+
+test_scl_usage "ceylon --version" "ceylon version"
+check_result $?
+test_connection
+check_result $?
+
+echo "Success!"
 cleanup
 
